// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication3.Data;

#nullable disable

namespace WebApplication1.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20240620204628_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0-preview.5.24306.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApplication3.Models.Backpack", b =>
                {
                    b.Property<int>("CharacterId")
                        .HasColumnType("int");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.HasKey("CharacterId", "ItemId");

                    b.HasIndex("ItemId");

                    b.ToTable("Backpack");

                    b.HasData(
                        new
                        {
                            CharacterId = 1,
                            ItemId = 1,
                            Amount = 3
                        },
                        new
                        {
                            CharacterId = 1,
                            ItemId = 2,
                            Amount = 4
                        },
                        new
                        {
                            CharacterId = 2,
                            ItemId = 1,
                            Amount = 5
                        },
                        new
                        {
                            CharacterId = 3,
                            ItemId = 2,
                            Amount = 8
                        });
                });

            modelBuilder.Entity("WebApplication3.Models.Character", b =>
                {
                    b.Property<int>("IdCharacter")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCharacter"));

                    b.Property<int>("CurrentWeight")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int>("MaxWeight")
                        .HasColumnType("int");

                    b.HasKey("IdCharacter");

                    b.ToTable("Character");

                    b.HasData(
                        new
                        {
                            IdCharacter = 1,
                            CurrentWeight = 3,
                            FirstName = "c1",
                            LastName = "cl1",
                            MaxWeight = 6
                        },
                        new
                        {
                            IdCharacter = 2,
                            CurrentWeight = 2,
                            FirstName = "c2",
                            LastName = "cl2",
                            MaxWeight = 7
                        },
                        new
                        {
                            IdCharacter = 3,
                            CurrentWeight = 1,
                            FirstName = "c3",
                            LastName = "cl3",
                            MaxWeight = 3
                        });
                });

            modelBuilder.Entity("WebApplication3.Models.CharacterTitle", b =>
                {
                    b.Property<int>("CharacterId")
                        .HasColumnType("int");

                    b.Property<int>("TitleId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("AcquiredId")
                        .HasColumnType("date");

                    b.HasKey("CharacterId", "TitleId");

                    b.HasIndex("TitleId");

                    b.ToTable("Character_Title");

                    b.HasData(
                        new
                        {
                            CharacterId = 1,
                            TitleId = 1,
                            AcquiredId = new DateOnly(2024, 5, 28)
                        },
                        new
                        {
                            CharacterId = 2,
                            TitleId = 1,
                            AcquiredId = new DateOnly(2024, 5, 31)
                        },
                        new
                        {
                            CharacterId = 3,
                            TitleId = 2,
                            AcquiredId = new DateOnly(2023, 6, 1)
                        });
                });

            modelBuilder.Entity("WebApplication3.Models.Item", b =>
                {
                    b.Property<int>("IdItem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdItem"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Weight")
                        .HasColumnType("int");

                    b.HasKey("IdItem");

                    b.ToTable("Item");

                    b.HasData(
                        new
                        {
                            IdItem = 1,
                            Name = "I1",
                            Weight = 3
                        },
                        new
                        {
                            IdItem = 2,
                            Name = "I2",
                            Weight = 4
                        });
                });

            modelBuilder.Entity("WebApplication3.Models.Title", b =>
                {
                    b.Property<int>("IdTitle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTitle"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdTitle");

                    b.ToTable("Title");

                    b.HasData(
                        new
                        {
                            IdTitle = 1,
                            Name = "t1"
                        },
                        new
                        {
                            IdTitle = 2,
                            Name = "t2"
                        });
                });

            modelBuilder.Entity("WebApplication3.Models.Backpack", b =>
                {
                    b.HasOne("WebApplication3.Models.Character", "Character")
                        .WithMany("Backpacks")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApplication3.Models.Item", "Item")
                        .WithMany("Backpacks")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("WebApplication3.Models.CharacterTitle", b =>
                {
                    b.HasOne("WebApplication3.Models.Character", "Character")
                        .WithMany("CharacterTitles")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApplication3.Models.Title", "Title")
                        .WithMany("CharacterTitles")
                        .HasForeignKey("TitleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("Title");
                });

            modelBuilder.Entity("WebApplication3.Models.Character", b =>
                {
                    b.Navigation("Backpacks");

                    b.Navigation("CharacterTitles");
                });

            modelBuilder.Entity("WebApplication3.Models.Item", b =>
                {
                    b.Navigation("Backpacks");
                });

            modelBuilder.Entity("WebApplication3.Models.Title", b =>
                {
                    b.Navigation("CharacterTitles");
                });
#pragma warning restore 612, 618
        }
    }
}
